# Transformacion de variables

## 1. Importar paquetes

In [40]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import StandardScaler, OneHotEncoder

## 2. Carga de los datos

In [41]:
ruta = 'C:/Users/matia/OneDrive/Escritorio/Energy_consumption'

In [42]:
nombre_cat = 'cat_resultado_calidad.pickle'
nombre_num = 'num_resultado_calidad.pickle'

In [43]:
cat = pd.read_pickle(ruta + '/02_Datos/03_Trabajo/' + nombre_cat)
num = pd.read_pickle(ruta + '/02_Datos/03_Trabajo/' + nombre_num)

In [44]:
num

,Usage_kWh,Lagging_Current_Reactive_Power_kVarh,Leading_Current_Reactive_Power_kVarh,Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,CO2_tCO2
95,3.42,3.46,0.00,70.30,100.00,0,0.0
0,3.17,2.95,0.00,73.21,100.00,900,0.0
1,4.00,4.46,0.00,66.77,100.00,1800,0.0
2,3.24,3.28,0.00,70.28,100.00,2700,0.0
3,3.31,3.56,0.00,68.09,100.00,3600,0.0
...,...,...,...,...,...,...,...
35034,3.82,4.54,0.00,64.38,100.00,81900,0.0
35035,3.85,4.86,0.00,62.10,100.00,82800,0.0
35036,3.74,3.74,0.00,70.71,100.00,83700,0.0
35037,3.78,3.17,0.07,76.62,99.98,84600,0.0
35038,3.78,3.06,0.11,77.72,99.96,85500,0.0

## 3. Transformar variable categoricas

Separamos la fecha, dado que no nos interesa transformarla

In [26]:
date = cat['date']
date = pd.DataFrame(date)

In [27]:
cat.drop(columns = ['date'], inplace = True)

Instanciar

In [28]:
ohe = OneHotEncoder(sparse_output = False, handle_unknown = 'ignore')

Aplicar

In [29]:
cat_ohe = ohe.fit_transform(cat)

Pasar todo a un dataset

In [30]:
cat_ohe = pd.DataFrame(cat_ohe, columns = ohe.get_feature_names_out())

## 4. Transformacion de variables numericas

Aplicamos una unica transformacion

In [45]:
variables = num.columns.to_list()
variables

['Usage_kWh',
 'Lagging_Current_Reactive_Power_kVarh',
 'Leading_Current_Reactive_Power_kVarh',
 'Lagging_Current_Power_Factor',
 'Leading_Current_Power_Factor',
 'NSM',
 'CO2_tCO2']

Instanciar

In [46]:
std_scaler = StandardScaler()

Aplicar

In [47]:
num = std_scaler.fit_transform(num)

Pasar a un dataset

In [50]:
nombres_num = [variable + '_std_' for variable in variables]

In [52]:
num = pd.DataFrame(num, columns = nombres_num)

## 5. Generar el dataset final y guardarlo

In [53]:
df_tablon = pd.concat([date, cat_ohe, num], axis = 1)

In [54]:
df_tablon

,date,WeekStatus_Weekday,WeekStatus_Weekend,Day_of_week_Friday,Day_of_week_Monday,Day_of_week_Saturday,Day_of_week_Sunday,Day_of_week_Thursday,Day_of_week_Tuesday,Day_of_week_Wednesday,Load_Type_Light_Load,Load_Type_Maximum_Load,Load_Type_Medium_Load,Usage_kWh_std_,Lagging_Current_Reactive_Power_kVarh_std_,Leading_Current_Reactive_Power_kVarh_std_,Lagging_Current_Power_Factor_std_,Leading_Current_Power_Factor_std_,NSM_std_,CO2_tCO2_std_
95,2018-01-01 00:00:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.709154,-0.556575,-0.521385,-0.666351,0.513268,1.714102,-0.71355
0,2018-01-01 00:15:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.716630,-0.587239,-0.521385,-0.543207,0.513268,-1.714102,-0.71355
1,2018-01-01 00:30:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.724105,-0.618516,-0.521385,-0.389410,0.513268,-1.678015,-0.71355
2,2018-01-01 00:45:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.699287,-0.525911,-0.521385,-0.729772,0.513268,-1.641929,-0.71355
3,2018-01-01 01:00:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.722012,-0.598278,-0.521385,-0.544264,0.513268,-1.605843,-0.71355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35034,2018-12-31 22:45:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.709154,-0.527751,-0.521385,-0.886740,0.513268,1.533670,-0.71355
35035,2018-12-31 23:00:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.704669,-0.521005,-0.521385,-0.856086,0.513268,1.569756,-0.71355
35036,2018-12-31 23:15:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.703772,-0.501380,-0.521385,-0.976587,0.513268,1.605843,-0.71355
35037,2018-12-31 23:30:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.707061,-0.570067,-0.521385,-0.521538,0.513268,1.641929,-0.71355
35038,2018-12-31 23:45:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.705865,-0.605024,-0.511957,-0.209188,0.512611,1.678015,-0.71355

In [55]:
ruta_df_tablon = ruta + '/02_Datos/03_Trabajo/' + 'df_tablon.pickle'

In [56]:
df_tablon.to_pickle(ruta_df_tablon)